### ISSUE TITLE
Libum not correctly installed/located on windows 10 pro?

### ISSUE THREAD

**Issue by natecermak** [sensapex/sensapex-py#21]
I am unable to run the test module or run `UMP.get_ump()`. Both present the error below:
```
PS C:\> python3 -m sensapex.test
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\ctypes\__init__.py", line 450, in __getattr__
    dll = self._dlltype(name)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'libum' (or one of its dependencies). Try using the full path with constructor syntax.
```

 libum.dll is present in Python312/site-packages/sensapex/, as is umpcli.exe. I am on python3.12, and have tried both local installs (`pip install -e <local-path-to-cloned-repo>`) and install from pypi (`pip3 install sensapex`). I am running Python 3.12.4, pip 24.1.1, sensapex-py==1.400.0.

 Any advice would be greatly appreciated. Thanks!

**Comment by jhuhtamaki** [comment]
sensapex.py attempts to load libum.dll from multiple locations sequentially; error handling of one of the steps does not work correctly: The ctypes.windll.libum raises AttributeError instead of expected OSError.

```
with contextlib.suppress(OSError):
  return ctypes.windll.libum
```

The behaviour was changed in [recent  Python release](https://github.com/python/cpython/issues/78997)
One possible workaround, that should work on old and new Python versions:

```
with contextlib.suppress(OSError, AttributeError):
  return ctypes.windll.libum
```

**Comment by outofculture** [comment]
Thanks for figuring this out, @jhuhtamaki! Fix is released.
